# Generated by Django 5.2.3 on 2025-06-17 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProductWarranty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warranty_start_date", models.DateField()),
                ("warranty_end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default="")),
                ("description", models.TextField(default="")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(upload_to="./media/customer_products_images/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_product_category",
                        to="customerproducts.customerproductcategory",
                    ),
                ),
                (
                    "warranty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_product_warranty",
                        to="customerproducts.customerproductwarranty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="")),
                ("description", models.CharField(default="")),
                (
                    "customer_product_feature_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_product_feature_section",
                        to="customerproducts.customerproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProductFeatureSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(default="")),
                (
                    "customer_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_product",
                        to="customerproducts.customerproduct",
                    ),
                ),
            ],
        ),
    ]
