# Generated by Django 5.2.3 on 2025-06-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customerproducts", "0002_remove_customerproduct_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerProductFeatureSection",
            new_name="CustomerFeatureSectionModel",
        ),
        migrations.RenameModel(
            old_name="CustomerProductCategory",
            new_name="CustomerProductCategoryModel",
        ),
        migrations.RenameModel(
            old_name="CustomerProductFeature",
            new_name="CustomerProductFeatureModel",
        ),
        migrations.RenameModel(
            old_name="CustomerProduct",
            new_name="CustomerProductModel",
        ),
        migrations.RenameModel(
            old_name="CustomerProductWarranty",
            new_name="CustomerProductWarrantyModel",
        ),
    ]
