# Generated by Django 5.2.3 on 2025-06-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customerproducts",
            "0003_rename_customerproductfeaturesection_customerfeaturesectionmodel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customerproductmodel",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="customerproductfeaturemodel",
            name="customer_product_feature_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_product_feature_section",
                to="customerproducts.customerfeaturesectionmodel",
            ),
        ),
    ]
